package HTML.behavior;

/*Generated by MPS */

import jetbrains.mps.core.aspects.behaviour.BaseBHDescriptor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.MetaAdapterFactory;
import jetbrains.mps.core.aspects.behaviour.api.BehaviorRegistry;
import jetbrains.mps.smodel.language.ConceptRegistry;
import jetbrains.mps.core.aspects.behaviour.api.SMethod;
import jetbrains.mps.core.aspects.behaviour.SMethodBuilder;
import jetbrains.mps.core.aspects.behaviour.SJavaCompoundTypeImpl;
import jetbrains.mps.core.aspects.behaviour.SModifiersImpl;
import jetbrains.mps.core.aspects.behaviour.AccessPrivileges;
import java.util.List;
import java.util.Arrays;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.mps.openapi.model.SNode;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SLinkOperations;
import jetbrains.mps.lang.smodel.generator.smodelAdapter.SPropertyOperations;
import jetbrains.mps.core.aspects.behaviour.api.SConstructor;
import org.jetbrains.annotations.Nullable;
import jetbrains.mps.core.aspects.behaviour.api.BHMethodNotFoundException;

public final class Garage_Project__BehaviorDescriptor extends BaseBHDescriptor {
  private static final SAbstractConcept CONCEPT = MetaAdapterFactory.getConcept(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b439L, "HTML.structure.Garage_Project");
  private static final BehaviorRegistry REGISTRY = ConceptRegistry.getInstance().getBehaviorRegistry();

  public static final SMethod<Integer> getExpenses_id7_nejbSeENP = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getExpenses").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("7_nejbSeENP").registry(REGISTRY).build();
  public static final SMethod<Integer> getPrice_id7_nejbSeSDb = new SMethodBuilder<Integer>(new SJavaCompoundTypeImpl(Integer.TYPE)).name("getPrice").modifiers(SModifiersImpl.create(0, AccessPrivileges.PUBLIC)).concept(CONCEPT).id("7_nejbSeSDb").registry(REGISTRY).build();

  private static final List<SMethod<?>> BH_METHODS = Arrays.<SMethod<?>>asList(getExpenses_id7_nejbSeENP, getPrice_id7_nejbSeSDb);

  private static void ___init___(@NotNull SNode __thisNode__) {
  }

  /*package*/ static int getExpenses_id7_nejbSeENP(@NotNull SNode __thisNode__) {
    int expenses = 0;
    for (SNode component : SLinkOperations.getChildren(__thisNode__, MetaAdapterFactory.getContainmentLink(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b439L, 0x79573932f835b440L, "components"))) {
      expenses += SPropertyOperations.getInteger(SLinkOperations.getTarget(component, MetaAdapterFactory.getReferenceLink(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b434L, 0x79573932f835b437L, "component")), MetaAdapterFactory.getProperty(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x3bf1ae90b86e7a5cL, 0x3bf1ae90b86e7a61L, "price")) * SPropertyOperations.getInteger(component, MetaAdapterFactory.getProperty(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b434L, 0x79573932f835b435L, "quantity"));
    }
    return expenses;
  }
  /*package*/ static int getPrice_id7_nejbSeSDb(@NotNull SNode __thisNode__) {
    return ((int) Garage_Project__BehaviorDescriptor.getExpenses_id7_nejbSeENP.invoke(__thisNode__)) * 2;
  }

  /*package*/ Garage_Project__BehaviorDescriptor() {
    super(REGISTRY);
  }

  @Override
  protected void initNode(@NotNull SNode node, @NotNull SConstructor constructor, @Nullable Object[] parameters) {
    ___init___(node);
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SNode node, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      case 0:
        return (T) ((Integer) getExpenses_id7_nejbSeENP(node));
      case 1:
        return (T) ((Integer) getPrice_id7_nejbSeSDb(node));
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @Override
  protected <T> T invokeSpecial0(@NotNull SAbstractConcept concept, @NotNull SMethod<T> method, @Nullable Object[] parameters) {
    int methodIndex = BH_METHODS.indexOf(method);
    if (methodIndex < 0) {
      throw new BHMethodNotFoundException(this, method);
    }
    switch (methodIndex) {
      default:
        throw new BHMethodNotFoundException(this, method);
    }
  }

  @NotNull
  @Override
  public List<SMethod<?>> getDeclaredMethods() {
    return BH_METHODS;
  }

  @NotNull
  @Override
  public SAbstractConcept getConcept() {
    return CONCEPT;
  }
}
