package CSS.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int CSS_Declaration = 0;
  public static final int CSS_Declaration_Block = 1;
  public static final int CSS_File = 2;
  public static final int CSS_Ruleset = 3;
  public static final int CSS_Selector = 4;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x8b04c156ec8d4138L, 0x9a8f46ff1babc15fL);
    builder.put(0x55762e27733a8cffL, CSS_Declaration);
    builder.put(0x55762e27733a8d05L, CSS_Declaration_Block);
    builder.put(0x55762e27733a8d11L, CSS_File);
    builder.put(0x55762e27733a8d0bL, CSS_Ruleset);
    builder.put(0x55762e27733a8d08L, CSS_Selector);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
