package HTML.editor;

/*Generated by MPS */

import jetbrains.mps.nodeEditor.EditorAspectDescriptorBase;
import org.jetbrains.annotations.NotNull;
import java.util.Collection;
import jetbrains.mps.openapi.editor.descriptor.ConceptEditor;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import java.util.Collections;
import jetbrains.mps.openapi.editor.descriptor.TransformationMenu;
import jetbrains.mps.openapi.editor.descriptor.SubstituteMenu;
import jetbrains.mps.lang.smodel.ConceptSwitchIndex;
import jetbrains.mps.lang.smodel.ConceptSwitchIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;

public class EditorAspectDescriptorImpl extends EditorAspectDescriptorBase {
  @NotNull
  public Collection<ConceptEditor> getDeclaredEditors(SAbstractConcept concept) {
    SAbstractConcept cncpt = ((SAbstractConcept) concept);
    switch (conceptIndex.index(cncpt)) {
      case 0:
        return Collections.<ConceptEditor>singletonList(new Component_Editor());
      case 1:
        return Collections.<ConceptEditor>singletonList(new Garage_Project_Editor());
      case 2:
        return Collections.<ConceptEditor>singletonList(new HtmlFile_Editor());
      case 3:
        return Collections.<ConceptEditor>singletonList(new Project_Component_Editor());
      case 4:
        return Collections.<ConceptEditor>singletonList(new Text_Line_Editor());
      case 5:
        return Collections.<ConceptEditor>singletonList(new Warehouse_Editor());
      default:
    }
    return Collections.<ConceptEditor>emptyList();
  }


  @NotNull
  @Override
  public Collection<TransformationMenu> getDeclaredDefaultTransformationMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex1.index(cncpt)) {
      case 0:
        return Collections.<TransformationMenu>singletonList(new Project_Component_TransformationMenu());
      default:
    }
    return Collections.<TransformationMenu>emptyList();
  }
  @NotNull
  @Override
  public Collection<SubstituteMenu> getDeclaredDefaultSubstituteMenus(SAbstractConcept concept) {
    SAbstractConcept cncpt = concept;
    switch (conceptIndex2.index(cncpt)) {
      case 0:
        return Collections.<SubstituteMenu>singletonList(new Project_Component_SubstituteMenu());
      default:
    }
    return Collections.<SubstituteMenu>emptyList();
  }

  private static final ConceptSwitchIndex conceptIndex = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x3bf1ae90b86e7a5cL), MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b439L), MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x3bf1ae90b86cea64L), MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b434L), MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b431L), MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x3bf1ae90b86e7a64L)).seal();
  private static final ConceptSwitchIndex conceptIndex1 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b434L)).seal();
  private static final ConceptSwitchIndex conceptIndex2 = new ConceptSwitchIndexBuilder().put(MetaIdFactory.conceptId(0x35b552000a684741L, 0xa7f945ec895812b7L, 0x79573932f835b434L)).seal();
}
